export { default as Navbar } from "../components/nav/Navbar"

export { default as Home } from "../components/home/Home"
export { default as Product } from "../components/product/Product"
export { default as SearchPage } from "../components/search/SearchPage"
export { default as Advance } from "../components/advance/Advance"
export { default as InfoProduct } from "../components/info-product/InfoProduct"
export { default as InfoRight } from "../components/info-right/Info-right"
export { default as Swiper } from "../components/swiper/Swiper"
export { default as WillTouch } from "../components/will-touch/WillTouch"
export { default as Footer } from "../components/footer/Footer"
export { default as HotelsList } from "../components/hotel-list/HotelsList"
export { default as MostLiked } from "../components/most-liked/MostLiked"
export { default as Reservation } from "../components/reservation/Reservation"
export { default as Cabinet } from "../components/cabinet/Cabinet"
export { default as Bonuses } from "../components/bonuses/Bonuses"
export {default as Register} from "../components/register/Register"